# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_messages_datetimeadded'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('classes', models.ManyToManyField(to='app.Classes')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Schools')),
            ],
        ),
        migrations.AlterField(
            model_name='messages',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
